// * Organization Action Constants *
export const GET_ORGANIZATION_LIST = 'GET_ORGANIZATION_LIST';
export const GET_ORGANIZATION_LIST_SUCCESS = 'GET_ORGANIZATION_LIST_SUCCESS';
export const GET_ORGANIZATION_LIST_FAILURE = 'GET_ORGANIZATION_LIST_FAILURE';

export const GET_ORGANIZATION_BY_ID = 'GET_ORGANIZATION_BY_ID';
export const GET_ORGANIZATION_BY_ID_SUCCESS = 'GET_ORGANIZATION_BY_ID_SUCCESS';
export const GET_ORGANIZATION_BY_ID_FAILURE = 'GET_ORGANIZATION_BY_ID_FAILURE';

export const GET_ORGANIZATIONS_BY_ORGANIZER_ID = 'GET_ORGANIZATIONS_BY_ORGANIZER_ID';
export const GET_ORGANIZATIONS_BY_ORGANIZER_ID_SUCCESS = 'GET_ORGANIZATIONS_BY_ORGANIZER_ID_SUCCESS';
export const GET_ORGANIZATIONS_BY_ORGANIZER_ID_FAILURE = 'GET_ORGANIZATIONS_BY_ORGANIZER_ID_FAILURE';

export const POST_ORGANIZATION = 'POST_ORGANIZATION';
export const POST_ORGANIZATION_SUCCESS = 'POST_ORGANIZATION_SUCCESS';
export const POST_ORGANIZATION_FAILURE = 'POST_ORGANIZATION_FAILURE';

export const PATCH_ORGANIZATION = 'PATCH_ORGANIZATION';
export const PATCH_ORGANIZATION_SUCCESS = 'PATCH_ORGANIZATION_SUCCESS';
export const PATCH_ORGANIZATION_FAILURE = 'PATCH_ORGANIZATION_FAILURE';

export const DELETE_ORGANIZATION = 'DELETE_ORGANIZATION';
export const DELETE_ORGANIZATION_SUCCESS = 'DELETE_ORGANIZATION_SUCCESS';
export const DELETE_ORGANIZATION_FAILURE = 'DELETE_ORGANIZATION_FAILURE';
// * END Organization Action Constants *

// * Event Action Constants *
export const GET_EVENT_LIST = 'GET_EVENT_LIST';
export const GET_EVENT_LIST_SUCCESS = 'GET_EVENT_LIST_SUCCESS';
export const GET_EVENT_LIST_FAILURE = 'GET_EVENT_LIST_FAILURE';

export const GET_EVENT_BY_ID = 'GET_EVENT_BY_ID';
export const GET_EVENT_BY_ID_SUCCESS = 'GET_EVENT_BY_ID_SUCCESS';
export const GET_EVENT_BY_ID_FAILURE = 'GET_EVENT_BY_ID_FAILURE';

export const GET_EVENTS_BY_ORGANIZATION_ID = 'GET_EVENTS_BY_ORGANIZATION_ID';
export const GET_EVENTS_BY_ORGANIZATION_ID_SUCCESS = 'GET_EVENTS_BY_ORGANIZATION_ID_SUCCESS';
export const GET_EVENTS_BY_ORGANIZATION_ID_FAILURE = 'GET_EVENTS_BY_ORGANIZATION_ID_FAILURE';

export const GET_NEXT_EVENT = 'GET_NEXT_EVENT';
export const GET_NEXT_EVENT_SUCCESS = 'GET_NEXT_EVENT_SUCCESS';
export const GET_NEXT_EVENT_FAILURE = 'GET_NEXT_EVENT_FAILURE';

export const POST_EVENT = 'POST_EVENT';
export const POST_EVENT_SUCCESS = 'POST_EVENT_SUCCESS';
export const POST_EVENT_FAILURE = 'POST_EVENT_FAILURE';

export const PATCH_EVENT = 'PATCH_EVENT';
export const PATCH_EVENT_SUCCESS = 'PATCH_EVENT_SUCCESS';
export const PATCH_EVENT_FAILURE = 'PATCH_EVENT_FAILURE';

export const DELETE_EVENT = 'DELETE_EVENT';
export const DELETE_EVENT_SUCCESS = 'DELETE_EVENT_SUCCESS';
export const DELETE_EVENT_FAILURE = 'DELETE_EVENT_FAILURE';
// * END Event Action Constants *

// * Event Member Action Constants *
export const GET_EVENT_MEMBERS = 'GET_EVENT_MEMBERS';
export const GET_EVENT_MEMBERS_SUCCESS = 'GET_EVENT_MEMBERS_SUCCESS';
export const GET_EVENT_MEMBERS_FAILURE = 'GET_EVENT_MEMBERS_FAILURE';

export const GET_EVENT_MEMBERS_BY_ID = 'GET_EVENT_MEMBERS_BY_ID';
export const GET_EVENT_MEMBERS_BY_ID_SUCCESS = 'GET_EVENT_MEMBERS_BY_ID_SUCCESS';
export const GET_EVENT_MEMBERS_BY_ID_FAILURE = 'GET_EVENT_MEMBERS_BY_ID_FAILURE';

export const POST_EVENT_MEMBER = 'POST_EVENT_MEMBER';
export const POST_EVENT_MEMBER_SUCCESS = 'POST_EVENT_MEMBER_SUCCESS';
export const POST_EVENT_MEMBER_FAILURE = 'POST_EVENT_MEMBER_FAILURE';

export const PATCH_EVENT_MEMBER = 'PATCH_EVENT_MEMBER';
export const PATCH_EVENT_MEMBER_SUCCESS = 'PATCH_EVENT_MEMBER_SUCCESS';
export const PATCH_EVENT_MEMBER_FAILURE = 'PATCH_EVENT_MEMBER_FAILURE';

export const CLAIM_EVENT_MEMBER = 'CLAIM_EVENT_MEMBER';
export const CLAIM_EVENT_MEMBER_SUCCESS = 'CLAIM_EVENT_MEMBER_SUCCESS';
export const CLAIM_EVENT_MEMBER_FAILURE = 'CLAIM_EVENT_MEMBER_FAILURE';

export const UNCLAIM_EVENT_MEMBER = 'UNCLAIM_EVENT_MEMBER';
export const UNCLAIM_EVENT_MEMBER_SUCCESS = 'UNCLAIM_EVENT_MEMBER_SUCCESS';
export const UNCLAIM_EVENT_MEMBER_FAILURE = 'UNCLAIM_EVENT_MEMBER_FAILURE';

export const DELETE_EVENT_MEMBER = 'DELETE_EVENT_MEMBER';
export const DELETE_EVENT_MEMBER_SUCCESS = 'DELETE_EVENT_MEMBER_SUCCESS';
export const DELETE_EVENT_MEMBER_FAILURE = 'DELETE_EVENT_MEMBER_FAILURE';
// * END Event Member Action Constants *

// * Event Chatroom Message Action Constants *
export const GET_EVENT_CHATROOM_MESSAGES = 'GET_EVENT_CHATROOM_MESSAGES';
export const GET_EVENT_CHATROOM_MESSAGES_SUCCESS = 'GET_EVENT_CHATROOM_MESSAGES_SUCCESS';
export const GET_EVENT_CHATROOM_MESSAGES_FAILURE = 'GET_EVENT_CHATROOM_MESSAGES_FAILURE';

export const POST_EVENT_CHATROOM_MESSAGE = 'POST_EVENT_CHATROOM_MESSAGE';
export const POST_EVENT_CHATROOM_MESSAGE_SUCCESS = 'POST_EVENT_CHATROOM_MESSAGE_SUCCESS';
export const POST_EVENT_CHATROOM_MESSAGE_FAILURE = 'POST_EVENT_CHATROOM_MESSAGE_FAILURE';

export const PATCH_EVENT_CHATROOM_MESSAGE = 'PATCH_EVENT_CHATROOM_MESSAGE';
export const PATCH_EVENT_CHATROOM_MESSAGE_SUCCESS = 'PATCH_EVENT_CHATROOM_MESSAGE_SUCCESS';
export const PATCH_EVENT_CHATROOM_MESSAGE_FAILURE = 'PATCH_EVENT_CHATROOM_MESSAGE_FAILURE';

export const DELETE_EVENT_CHATROOM_MESSAGE = 'DELETE_EVENT_CHATROOM_MESSAGE';
export const DELETE_EVENT_CHATROOM_MESSAGE_SUCCESS = 'DELETE_EVENT_CHATROOM_MESSAGE_SUCCESS';
export const DELETE_EVENT_CHATROOM_MESSAGE_FAILURE = 'DELETE_EVENT_CHATROOM_MESSAGE_FAILURE';
// * END Event Chatroom Message Action Constants *

// * User Action Constants *
export const GET_USER = 'GET_USER';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAILURE = 'GET_USER_FAILURE';
// * END User Action Constants *